[package]
name = "rvid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
clap = "4.4.12"
raw_tty = "0.1.0"
termios = "0.3.3"
thiserror = "1.0.52"
libc = "0.2.151"
